'use strict';

var gamename = {

"1999 (1987)(Alternative Software)": "1999 (1987)(Summit Software [1])",
"1999 (1987)(Alternative Software)[a2]": "1999 (1987)(Summit Software [1])[a2]",
"1999 (1987)(Alternative Software)[a]": "1999 (1987)(Summit Software [1])[a]",
"1999 (1987)(Alternative Software)[h Prophecy]": "1999 (1987)(Summit Software [1])[h Prophecy]",
"20 Tons (1985)(Argus Press Software)": "20 Tons (1985)(Spectrum Computing)",
"20 Tons (1985)(Argus Press Software)[h Jupiter 77][t]": "20 Tons (1985)(Spectrum Computing)[h Jupiter 77][t]",
"3D Labyrint (1989)(Busy Software - Fuxoft)": "Labyrinth, 3D (1989)(Busy Software)",
"3D Labyrint (1989)(Busy Software - Fuxoft)[a]": "3D Labyrint (1989)(Busy Software)[a]",
"3D Labyrint (1989)(Busy Software - Fuxoft)[h Flash][t]": "3D Labyrint (1989)(Busy Software)[h Flash][t]",
"3D Labyrint (1989)(Busy Software - Fuxoft)[h Jupiter 77]": "Labyrinth, 3D (1989)(Busy Software)[h Jupiter 77]",
"3D Pool (1989)(Firebird Software)[h Beermans - Magic Soft]": "Pool, 3D (1989)(Firebird Software)[h Beermans - Magic Soft]",
"3D-Quadracube (1983)(Forward Software)[16K][re-release]": "Quadracube, 3D (1983)(Artic Computing Ltd)[16K][re-release]",
"A Tangled Tale (1985)(Double Play Adventures)": "A Tangled Tale (1985)(D. Watson)",
"A Tangled Tale (1985)(Double Play Adventures)[a]": "A Tangled Tale (1985)(D. Watson)[a]",
"A.R.N.O.L.D. (1988)(Static Soft)(es)":"Arnold (1988)(Static Soft)(es)", 
"A.T.F. (1988)(Digital Integration)": "ATF (1988)(Digital Integration)",
"Abe's Mission - Escape (demo) (2002)(Bothers)(ru)": "Abe's Mission: Escape (demo) (2002)(Bothers)(ru)",
"Abu Simbel Profanation (1986)(Erbe Software)(ES)[a][re-release]": "Abu Simbel Profanation (1986)(Dinamic Software)(ES)[a][re-release]",
"Abu Simbel Profanation (1986)(Erbe Software)(es)[re-release]": "Abu Simbel Profanation (1986)(Dinamic Software)(es)[re-release]",
"Acro Jet (1986)(U.S. Gold)": "Acro Jet (1986)(MicroProse Software Ltd)",
"Acro Jet (1986)(U.S. Gold)[a2]": "Acro Jet (1986)(MicroProse Software Ltd)[a2]",
"Acro Jet (1986)(U.S. Gold)[a3]": "Acro Jet (1986)(MicroProse Software Ltd)[a3]",
"Acro Jet (1986)(U.S. Gold)[a4]": "Acro Jet (1986)(MicroProse Software Ltd)[a4]",
"Acro Jet (1986)(U.S. Gold)[a5]": "Acro Jet (1986)(MicroProse Software Ltd)[a5]",
"Acro Jet (1986)(U.S. Gold)[a]": "Acro Jet (1986)(MicroProse Software Ltd)[a]",
"Action Force II (1988)(Virgin Mastertronic)[h Extreme][t]": "Action Force II (1988)(Virgin Games Ltd)[h Extreme][t]",
"Air Brush (1983)(Soft Hits)": "Airbrush (1983)(Soft Hits)",
"Air Brush (1983)(Soft Hits)[a]": "Airbrush (1983)(Soft Hits)[a]",
"Air Force (1984)(Piper Books)": "Air Force (1984)(Piper Software)",
"Airwolf (1985)(Zafiro Software Division)": "Airwolf (1985)(Zafi Chip)",
"Ammytris, The (1996)(Tsunami Group)(ru)":"Ammytris, The (1996)(Navigator)(ru)", 
"Aqua Squad (1988)(Atlantis Software)": "Aquasquad (1988)(Atlantis Software)",
"Ares (1990)(Mixt Software)(es)": "Ares (1990)(MicroHobby)(es)",
"Asalto Y Castigo (2009)(el Arquero, Baltasar)(ES)": "Asalto y Castigo (2009)(Baltasar el Arquero)(ES)",
"Asteroidy (1983)(Fontana Publishing)(cs)[16K][aka Asteroid Belt]": "Asteroid Belt (1983)(Usborne Publishing Ltd)(cs)[16K][aka Asteroid Belt]",
"Astronaut (19xx)(-)(nl)": "S.O.R.T. (1984)(Mirrorsoft Ltd)(nl)",
"ATF - Advanced Tactical Fighter (1988)(Digital Integration)[h Jupiter 77][t]": "Advanced Tactical Fighter (1988)(Digital Integration)[h Jupiter 77][t]",
"ATRAM (1984)(Websters Software)": "A.T.R.A.M (1984)(Websters Software)",
"ATRAM (1984)(Websters Software)[a]":"A.T.R.A.M (1984)(Websters Software)[a]", 
"Attacker (1983)(Cascade Games)[16K]":"Attacker (1983)(U.T.S.)[16K]", 
"Attacker (1983)(Cascade Games)[a][16K]":"Attacker (1983)(U.T.S.)[a][16K]",
"Auto Kursiv (1987)(W. Janowsky)": "Auto Kursiv (1987)(Klaus Jahn)",
"Averno (1989)(Proein Soft Line)(es)": "Averno (1989)(P.J. Software)(es)",
"Awari (1984)(Orbis Publishing)[16K]": "Awari (1984)(The Home Computer Advanced Course)[16K]",
"Awari (1984)(Orbis Publishing)[a][16K]": "Awari (1984)(The Home Computer Advanced Course)[a][16K]",
"Banda, La (1985)(Stars)(es)[aka Everyone's a Wally]":"Everyone's a Wally (1985)(Mikro-Gen Ltd)(es)[aka Everyone's a Wally]", 
"Bargain Basement (1986)(Creative Sparks)": "Bargain Basement (1986)(Sparklers)",
"Bargain Basement (1986)(Creative Sparks)[a]":"Bargain Basement (1986)(Sparklers)[a]", 
"Bargain Basement (1986)(Creative Sparks)[cr Blood]": "Bargain Basement (1986)(Sparklers)[cr Blood]",
"Baron Rojo (1984)(Zafiro Software Division)":"Baron Rojo (1984)(Zafi Chip)", 
"Baron Rojo (1984)(Zafiro Software Division)(es)[aka Red Baron]": "Red Baron (1984)(Zafi Chip)(es)[aka Red Baron]",
"Barrel Jump (1983)(Cascade Games)[16K]":"Barrel Jump (1983)(U.T.S.)[16K]",  
"Barrel Jump (1983)(Cascade Games)[a][16K]":"Barrel Jump (1983)(U.T.S.)[a][16K]", 
"Basic Rally (2005)(Master Games)":"BASIC Rally (2005)(Masters Games)", 
"Bazooka Bill (1986)(Arcade Software)[re-release]":"Bazooka Bill (1986)(Melbourne House)[re-release]", 
"Bear George (1984)(Cheetasoft)": "Bear George (1984)(CheetahSoft Ltd)",
"Bennie the Burglar (1987)(MB - APG Software)": "Bennie the Burglar (1987)(Players Software)",
"Black Arrow (1986)(Coyote Software)": "Black Arrow (1986)(Uros Justin)",
"Black Arrow (1986)(Coyote Software)[a]": "Black Arrow (1986)(Uros Justin)[a]", 
"Black Raven - Mission Editor (demo) (19xx)(Paladin)(ru)":"Black Raven Mission Editor (demo) (19xx)(Compu-Studio Ltd)(ru)", 
"Blackbeard (1988)(Topo Soft)(es)": "Black Beard (1988)(Topo Soft)(es)",
"Blackbeard (1988)(Topo Soft)(es)[a2]":"Black Beard (1988)(Topo Soft)(es)[a2]", 
"Blackbeard (1988)(Topo Soft)(es)[a]":"Black Beard (1988)(Topo Soft)(es)[a]", 
"Blackbeard (1988)(Topo Soft)(es)[Multiface copy]":"Black Beard (1988)(Topo Soft)(es)[Multiface copy]", 
"Blackbeard (1989)(Kixx)[a2][re-release]":"Black Beard (1989)(Kixx)[a2][re-release]", 
"Blackbeard (1989)(Kixx)[a2][re-release]":"Black Beard (1989)(Kixx)[a2][re-release]", 
"Blackbeard (1989)(Kixx)[a3][re-release]":"Black Beard (1989)(Kixx)[a3][re-release]", 
"Blackbeard (1989)(Kixx)[a][re-release]":"Black Beard (1989)(Kixx)[a][re-release]", 
"Blackbeard (1989)(Kixx)[a][re-release]":"Black Beard (1989)(Kixx)[a][re-release]", 
"Blackbeard (1989)(Kixx)[h Fatality][t][re-release]": "Black Beard (1988)(Topo Soft)(es)",
"Blackbeard (1989)(Kixx)[re-release]":"Black Beard (1989)(Kixx)[re-release]", 
"Blackbeard (1989)(Kixx)[re-release]":"Black Beard (1989)(Kixx)[re-release]", 
"Bob's Full House (1988)(Domark)": "Bob's Full House (1988)(TV Games)",
"Bob's Full House (1988)(Domark)(Side A)":"Bob's Full House (1988)(TV Games)(Side A)",  
"Bob's Full House (1988)(Domark)(Side B)":"Bob's Full House (1988)(TV Games)(Side B)", 
"Boggles (1983)(Cascade Games)[16K]":"Boggles (1983)(U.T.S.)[16K]",  
"Boggles (1983)(Cascade Games)[a2][16K]":"Boggles (1983)(U.T.S.)[a2][16K]", 
"Boggles (1983)(Cascade Games)[a][16K]":"Boggles (1983)(U.T.S.)[a][16K]", 
"Bombfusion (1989)(Virgin Mastertronic)": "Bombfusion (1989)(Mastertronic Ltd)",
"Bombfusion (1989)(Virgin Mastertronic)[a2]":"Bombfusion (1989)(Mastertronic Ltd)[a2]", 
"Bombfusion (1989)(Virgin Mastertronic)[a]": "Bombfusion (1989)(Mastertronic Ltd)[a]",
"Book of the Dead (1987)(CRL - Essential Myth)[3556]": "Book of the Dead (1987)(The Essential Myth)[3556]",
"Borzak (1984)(Zafiro Software Division)(es)[re-release]":"Borzak (1984)(Zafi Chip)(es)[re-release]", 
"Borzak (1984)(Zafiro Software Division)(es)[re-release]":"Borzak (1984)(Zafi Chip)(es)[re-release]", 
"Boun Zai (1986)(Centaurisoft)":"Bounzai (1986)(Centaurisoft)",  
"Boun Zai (1986)(Centaurisoft)[a]":"Bounzai (1986)(Centaurisoft)[a]", 
"Bowling 2000 (1985)(Proxima Software)(cs)": "Bowling 2000 (1985)(Fuxoft )(cs)",
"Bowling 2000 (1992)(Proxima Software)(cs)":"Bowling 2000 (1992)(Fuxoft)(cs)", 
"Bowling 2000 (1992)(Proxima Software)(cs)":"Bowling 2000 (1992)(Fuxoft)(cs)", 
"Brood Slayer (1984)(CCS)":"Broodslayer (1984)(CCS)", 
"Brood Slayer (1984)(CCS)[a]":"Broodslayer (1984)(CCS)[a]", 
"Bubble Buster (1983)(Bubble Buster)": "Bubble Buster (1983)(Sinclair Research)",
"Bulls Eye (1984)(Macsen Software)": "Bullseye (1984)(Macsen Software)",
"Bulls Eye (1984)(Macsen Software)[a2]": "Bullseye (1984)(Macsen Software)[a2]",
"Bulls Eye (1984)(Macsen Software)[a]": "Bullseye (1984)(Macsen Software)[a]",
"Bulls Eye (1984)(TV Games)[re-release]": "Bullseye (1984)(TV Games)[re-release]",
"Campo Explosivo (1983)(Monser)(es)[aka Mined-Out]": "Mined-Out (1983)(Quicksilva Ltd)(es)",
"Cannibals (1987)(Alternative Software)":"Cannibals (1987)(Summit Software [1])", 
"Cannibals (1987)(Alternative Software)":"Cannibals (1987)(Summit Software [1])", 
"Cannibals (1987)(Alternative Software)[a]":"Cannibals (1987)(Summit Software [1])[a]", 
"Cannibals (1987)(Alternative Software)[cr]": "Cannibals from Outer Space (1987)(Summit Software [1])[cr]",
"Cannibals (1987)(Alternative Software)[cr][a]": "Cannibals from Outer Space (1987)(Summit Software [1])[cr][a]",
"Car-Slide-Race (1983)(Prospek Computing Cooperation)(de)":"Car-Slide-Race (1983)(Supersoft [3])(de)", 
"Car-Slide-Race (1983)(Prospek Computing Cooperation)(de)[a]":"Car-Slide-Race (1983)(Supersoft [3])(de)[a]", 
"Cash Cade (1990)(Fastback)": "Cashcade (1990)(Fastback)",
"Cave Flyer (19xx)(-)(de)": "Cave Flyer (19xx)(Friedrich Zohmann)(de)",
"Cazafantasmas (1984)(Stars)(es)[aka Ghostbusters]": "Ghostbusters (1984)(Activision Inc)(es)[aka Ghostbusters]",
"Chicago 30's (1988)(Topo Soft - U.S. Gold)[3558]": "Chicago 30's (1988)(Topo Soft)[3558]",
"Chinese Patience (1987)(Zafiro Software Division)[re-release]":"Chinese Patience (1987)(Z Cobra)[re-release]", 
"Chockman (1983)(Hyperion Software)": "Chocman (1983)(Hyperion Software)",
"City of Ehdollah, The (1984)(Dorling Kindersley Software)": "City of 'Ehdollah, The (1984)(Goldstar)",
"City of Ehdollah, The (1984)(Dorling Kindersley Software)[a2]":"City of Ehdollah, The (1984)(Goldstar)[a2]", 
"City of Ehdollah, The (1984)(Dorling Kindersley Software)[a]":"City of Ehdollah, The (1984)(Goldstar)[a]", 
"City of Ehdollah, The (1984)(Dorling Kindersley Software)[a]":"City of Ehdollah, The (1984)(Goldstar)[a]", 
"Cobble 2 (1999)(Nagual)":"Cobble 2 (1999)(V. Cheprasov)", 
"Computer Bridge (1983)(P.White)": "CSuper Bridge (1983)(Buffer Micro Ltd)",
"Crime of the Santa Claus Deja Vu 1 (1996)(ETC Group)(ru)[h FFC Computers - Softstar]": "Crime of the Santa Claus: Deja Vu (1996)(BrokImSoft)(ru)[h FFC Computers - Softstar]",
"Dargon's Crypt (1987)(Venom Games)":"Dargonscrypt (1987)(Venom Games)", 
"Dark, The (1994)(Hazis Sergey)":"Dark, The (1994)(Izhevsk)", 
"Daylight Robbery (2002)(Naffsoft)":"Daylight Robbery (2002)(Sinclair Research Ltd)", 
"Deactivators (1986)(Firebird Software)[re-release]":"Deactivators (1986)(Reaktor)[re-release]", 
"Decor Wreckers (1984)(Scorpio Software)": "Decor Wreckers (1984)(Andrew Reed)",
"Decor Wreckers (1984)(Scorpio Software)[a]":"Decor Wreckers (1984)(Andrew Reed)[a]", 
"Decor Wreckers (1984)(Scorpio Software)[a]":"Decor Wreckers (1984)(Andrew Reed)[a]", 
"Destruction of the Galactic Empire, The (1984)(David Ashton - Grant Wilson)": "Destruction of the Galactic Empire, The (1984)(David Ashton)",
"Devil's Descent, The (1987)(Video Vault)[re-release]": "Devil's Descent (1987)(Pocket Money Software)[re-release]",
"Diamonds Downfall (1994)(Power Software)":"Diamonds Downfall (1994)(Oleg Pritula)", 
"Dictador, El (1983)(DK'Tronics)(es)[aka Dictator]":"Dictador (1983)(DK'Tronics)(es)[aka Dictator]", 
"Docker Dan (19xx)(Wizard Software)": "Docker Dan (19xx)(Stewart Fordyce)",
"Dominator (1989)(Electric Dreams Software)": "Dominator (1989)(System 3 Software Ltd)",
"Dominator (1989)(Electric Dreams Software)[a]": "Dominator (1989)(System 3 Software Ltd)[a]",
"Dominator (1989)(Electric Dreams Software)[a][SpeedLock 7]":"Dominator (1989)(System 3 Software Ltd)[a][SpeedLock 7]", 
"Dominator (1989)(Electric Dreams Software)[SpeedLock 7]":"Dominator (1989)(System 3 Software Ltd)[SpeedLock 7]", 
"Dominator (1989)(Electric Dreams Software)[t][128K]":"Dominator (1989)(System 3 Software Ltd)[t][128K]", 
"Down Town (1991)(Atlantis Software)":"Downtown (1991)(Atlantis Software)", 
"Down Town (1991)(Atlantis Software)[a]":"Downtown (1991)(Atlantis Software)[a]", 
"Dr. Maddo (1986)(U.S. Gold)": "Dr. Maddo (1986)(Americana Software Ltd)",
"Dr. Maddo (1986)(U.S. Gold)[a2]":"Dr. Maddo (1986)(Americana Software Ltd)[a2]", 
"Dr. Maddo (1986)(U.S. Gold)[a]":"Dr. Maddo (1986)(Americana Software Ltd)[a]", 
"Dragon Slayer (1984)(Double Play Adventures)": "Dragon Slayer (1984)(Pocket Money Software)",
"Dragon Spirit (1989)(MP)[48-128K][re-release]": "Dragon Spirit (1989)(Domark Ltd)[48-128K][re-release]",
"Dragon's Gold (1983)(Cascade Games)[16K]":"Dragon's Gold (1983)(ZX Computing)[16K]", 
"Dragon's Gold (1983)(Cascade Games)[a][16K]":"Dragon's Gold (1983)(ZX Computing)[a][16K]", 
"Driller (1987)(Erbe Software)[re-release]":"Driller (1987)(Incentive Software Ltd)[re-release]", 
"Dunlop 911TS (1985)(Elite Systems)":"911 TS (1985)(Elite Systems Ltd)", 
"Durak 2 (1994)(New Hakers-Krouwait System)(ru)":"Durak 2 (1994)(Copper Feet)(ru)",
"Dustin (1988)(Hewson Consultants)[h Ascendancy][re-release]": "Dustin (1988)(Dinamic Software)[h Ascendancy][re-release]",
"Dustin (1988)(Hewson Consultants)[re-release]": "Dustin (1988)(Dinamic Software)[re-release]",
"Dyktator (1983)(DK'Tronics)(ru)[a][aka Dictator]": "Dictator (1983)(DK'Tronics)(ru)[a][aka Dictator]",
"Dyktator (1983)(DK'Tronics)(ru)[aka Dictator]": "Dictator (1983)(DK'Tronics)(ru)[aka Dictator]",
"East Enders (1986)(Macsen Software)": "EastEnders (1986)(Macsen Software)",
"East Enders (1987)(Macsen Software)":"EastEnders (1987)(Macsen Software)", 
"East Enders (1987)(Macsen Software)":"EastEnders (1987)(Macsen Software)", 
"East Enders (1987)(Macsen Software)[a]":"EastEnders (1987)(Macsen Software)[a]", 
"Elite - Character Designer (1987)(Igg)":"Elite - Character Designer (1987)(ZZKJ)", 
"Elite - Character Designer (1987)(Igg)[a2]":"Elite - Character Designer (1987)(ZZKJ)[a2]", 
"Elite - Character Designer (1987)(Igg)[a]":"Elite - Character Designer (1987)(ZZKJ)[a]", 
"Emilio Butragueno Futbol (1987)(Topo Soft - Ocean)(es)": "Emilio Butragueno Futbol (1987)(Topo Soft)(es)",
"Emilio Butragueno Futbol II (1989)(Erbe Software - Ocean)(es)": "Emilio Butragueno Futbol II (1989)(Erbe Software S.A.)(es)",
"Emilio Butragueno Futbol II (1989)(Erbe Software - Ocean)(es)[48-128K]":"Emilio Butragueno Futbol 2 (1989)(Erbe Software - Ocean)(es)[48-128K]", 
"Emilio Butragueno Futbol II - Campeonato (1989)(Erbe Software - Ocean)(es)":"Emilio Butragueno Futbol 2 - Campeonato (1989)(Erbe Software - Ocean)(es)", 
"Emilio Butragueno Futbol II - Campeonato (1989)(Erbe Software - Ocean)(es)[48-128K]":"Emilio Butragueno Futbol 2 - Campeonato (1989)(Erbe Software - Ocean)(es)[48-128K]", 
"Emilio Butragueno Futbol II - Campeonato (1989)(Erbe Software - Ocean)(es)[a][48-128K]": "Emilio Butragueno Futbol 2 - Campeonato (1989)(Erbe Software - Ocean)(es)[a][48-128K]", 
"Emilio Butragueno Futbol II - Campeonato (1989)(Erbe Software - Ocean)(es)[b]":"Emilio Butragueno Futbol 2 - Campeonato (1989)(Erbe Software - Ocean)(es)[b]", 
"Emilio Butragueno Futbol II - Entrenamiento (1989)(Erbe Software - Ocean)(es)[48-128K]":"Emilio Butragueno Futbol 2 - Entrenamiento (1989)(Erbe Software - Ocean)(es)[48-128K]", 
"Erik - The Phantom of the Opera (1987)(1.99 Range)[re-release]":"Erik: Phantom of the Opera (1987)(Crysys)[re-release]", 
"Escape to Eskelos (1987)(Gilsoft International)": "Deliverer 2: Escape to Eskelos (1987)(Brian Parks)",
"Espejos (1989)(Pedro Jose Rodriguez - Raul Lopez)(es)": "Espejos (1989)(Pedro Jose Rodriguez Larranaga)(es)",
"Fahrenheit 3000 (1985)(Silverbird Software)":"Fahrenheit 3000 (1985)(Softstone Ltd)", 
"Fahrenheit 3000 (1985)(Silverbird Software)":"Fahrenheit 3000 (1985)(Softstone Ltd)", 
"Fahrenheit 3000 (1985)(Silverbird Software)[a]":"Fahrenheit 3000 (1985)(Softstone Ltd)[a]", 
"Fakultet (1987)(Samir Ribic)(bs)": "Fakultet (1987)(Ribic Samir)(bs)",
"Fakultet (1987)(Samir Ribic)(bs)[a]":"Fakultet (1987)(Ribic Samir)(bs)[a]",
"Fall Of Rome, The (1984)(Power Software)(es)[re-release]":"Fall Of Rome, The (1984)(Power Software S.A.)(es)[re-release]",
"Filemon (1986)(Leczek Krecielewski)(pl)": "Filemon (1986)(Leszek Krecielewski)(pl)",
"Fisherman's Friend (1996)(JA Software)":"Fisherman's Friend (1996)(JJoseph Aron)", 
"Fisherman's Friend (1996)(JA Software)[48-128K]": "Fisherman's Friend (1996)(Joseph Aron)[48-128K]",
"Fisherman's Friend (1996)(JA Software)[a]":"Fisherman's Friend (1996)(Joseph Aron)[a]", 
"Fisherman's Friend (1996)(JJoseph Aron)":"Fisherman's Friend (1996)(Joseph Aron)", 
"Flash Point (1987)(Ocean)[a]": "Flashpoint (1987)(Ocean)[a]",
"Frankenstein Jnr (1990)(Codemasters)": "Frankenstein Jnr (1990)(Cartoon Time)",
"Frankenstein Jnr (1990)(Codemasters)[a]":"Frankenstein Jnr (1990)(Cartoon Time)[a]", 
"Frankenstein Jnr (1990)(Codemasters)[a]":"Frankenstein Jnr (1990)(Cartoon Time)[a]", 
"Fred's Fan Factory (1984)(Software Projects)":"Fred's Fan Factory (1984)(Software Supersavers Ltd)", 
"Fred's Fan Factory (1984)(Software Projects)":"Fred's Fan Factory (1984)(Software Supersavers Ltd)", 
"Fred's Fan Factory (1984)(Software Projects)[a]":"Fred's Fan Factory (1984)(Software Supersavers Ltd)[a]", 
"Frightful (1989)(Zigurat Software)(es)": "Frightful (1989)(NF Stars)(es)",
"Fuck Communistov! (19xx)(3S Group)(ru)":"Fuck Communistov! (19xx)(Lava)(ru)", 
"Fumigator (1984)(Monser)[aka Pssst]":"Pssst (1984)(Ultimate Play The Game)[aka Pssst]", 
"Future Zoo (1986)(Clwyd Adventure Software)":"Futurezoo (1986)(Clwyd Adventure Software)", 
"Geister Fahrer (1983)(Klaus Kopecz)(de)": "Geister Fahrer (1983)(Klaus Copecz)(de)",
"Giliszta (1993)(Egmont & Albert Koblinger)(hu)": "Giliszta (1993)(Albert Koblinger)(hu)",
"Goa 4k Intro (1998)(Extreme)": "Goa 4k Intro (1998)(VAV)",
"Goolf's Return (1984)(Green Fish Software Enterprise)": "Goolf Returns (1984)(Green Fish Software Enterprise)",
"Grande Fuga, La (1985)(Turbo Game)(it)[a][aka Monty is Innocent]": "Monty is Innocent (1985)(Gremlin Graphics Software Ltd)(it)[a][aka Monty is Innocent]",
"Grande Fuga, La (1985)(Turbo Game)(it)[aka Monty is Innocent]": "Monty is Innocent (1985)(Gremlin Graphics Software Ltd)(it)[aka Monty is Innocent]",
"Gricko (1982)(R&R Software)(sr)": "Gnasher (1982)(R&R Software Ltd)(sr)",
"Gricko (1982)(R&R Software)(sr)[a]":"Gnasher (1982)(R&R Software Ltd)(sr)[a]", 
"Gunlaw (1983)(Aackosoft)[16K][re-release]":"Gun Law (1983)(Vortex Software)[16K][re-release]", 
"Gunlaw (1983)(Vortex Software)":"Gun Law (1983)(Vortex Software)", 
"Gunlaw (1983)(Vortex Software)[16K]": "Gun Law (1983)(Vortex Software)[16K]",
"Guppi (1987)(Andrew Daly)": "Guppi (1987)(Andrew Mark Daly)",
"Hare Raiser (1984)(Haresoft)": "Hareraiser (1984)(Haresoft Ltd)",
"Hare Raiser (1984)(Haresoft)(Part 1 of 2)":"Hareraiser (1984)(Haresoft Ltd)(Part 1 of 2)", 
"Hare Raiser (1984)(Haresoft)(Part 1 of 2)[a]":"Hareraiser (1984)(Haresoft Ltd)(Part 1 of 2)[a]", 
"Hare Raiser (1984)(Haresoft)(Part 2 of 2)":"Hareraiser (1984)(Haresoft Ltd)(Part 2 of 2)", 
"Hare Raiser (1984)(Haresoft)(Side A)": "Hareraiser (1984)(Haresoft Ltd)(Side A)",
"Hare Raiser (1984)(Haresoft)(Side B)": "Hareraiser (1984)(Haresoft Ltd)(Side B)",
"Hare Raiser (1984)(Haresoft)[b]": "Hareraiser: Finale (1984)(Haresoft Ltd)[b]",
"Head Start (1987)(Bug-Byte Software)": "Headstart (1987)(Bug-Byte Software)",
"Head Start (1987)(Bug-Byte Software)[a]":"Headstart (1987)(Bug-Byte Software)[a]", 
"Head Start (1987)(Bug-Byte Software)[m]":"Headstart (1987)(Bug-Byte Software)[m]", 
"Hero (1984)(Activision)": "H.E.R.O. (1984)(Activision)",
"Hero (1984)(Activision)[a]": "H.E.R.O. (1984)(Activision)[a]",
"Hive (1986)(Capsoft - Softy)": "Hive (1986)(Capsoft)",
"Ian's Night Out (19xx)(Software Projects)": "Ian's Night Out (19xx)(Magnum Computing)",
"ID (1986)(CRL Group)": "ID (1986)(Nu Wave Software)",
"ID (1986)(CRL Group)[a]": "ID (1986)(Nu Wave Software)[a]",
"Indiana Jones y el Idolo de Oro (1985)(J.J. Sanchez)(es)": "Indiana Jones y el Idolo de Oro (1985)(MicroHobby)(es)",
"Infection (1989)(Virgin Mastertronic)[128K][unpublished]":"Infection (1989)(H-2-O Ltd)[128K][unpublished]", 
"Infection (1989)(Virgin Mastertronic)[48-128K][unpublished]":"Infection (1989)(H-2-O Ltd)[48-128K][unpublished]", 
"Infection (1989)(Virgin Mastertronic)[h Digital Reality][unpublished]": "Infection (1989)(H-2-O Ltd)[h Digital Reality][unpublished]",
"Infection (1989)(Virgin Mastertronic)[h Flash][unpublished]": "Infection (1989)(H-2-O Ltd)[h Flash][unpublished]",
"Infection (1989)(Virgin Mastertronic)[unpublished]":"Infection (1989)(H-2-O Ltd)[unpublished]", 
"Infrared (1982)(ACS Software)": "Infrared (1982)(Elettronica CS)",
"Infrared (1982)(ACS Software)[16K]": "Infrared (1982)(Elettronica CS)[16K]",
"Infrared (1982)(ACS Software)[a2]": "Infrared (1982)(Elettronica CS)[a2]",
"Infrared (1982)(ACS Software)[a]": "Infrared (1982)(Elettronica CS)[a]",
"Infrared (1982)(ACS Software)[a][16K]": "Infrared (1982)(Elettronica CS)[a][16K]",
"Invincible Island (1983)(Richard Shepard Software)": "Invincible Island (1983)(Richard Shepard Software)",
"Jet Set Willy III (1985)(MB - APG Software)": "JetSet Willy III (1985)(APG Software)", 
"Jet Set Willy III (1985)(MB - APG Software)": "JetSet Willy III (1985)(APG Software)", 
"Jet Set Willy III (1985)(MB - APG Software)[a2]": "JetSet Willy III (1985)(APG Software)[a2]", 
"Jet Set Willy III (1985)(MB - APG Software)[a]": "JetSet Willy III (1985)(APG Software)[a]", 
"Jet Set Willy III (1985)(MB - APG Software)[cr]": "JetSet Willy III (1985)(APG Software)[cr]",
"Journey's End (1985)(Mastertronic)(Part 1 of 3)":"Journey's End (1985)(Games Workshop)(Part 1 of 3)", 
"Journey's End (1985)(Mastertronic)(Part 1 of 3)":"Journey's End (1985)(Games Workshop)(Part 1 of 3)", 
"Journey's End (1985)(Mastertronic)(Part 1 of 3)[a2]":"Journey's End (1985)(Games Workshop)(Part 1 of 3)[a2]", 
"Journey's End (1985)(Mastertronic)(Part 1 of 3)[a]":"Journey's End (1985)(Games Workshop)(Part 1 of 3)[a]", 
"Journey's End (1985)(Mastertronic)(Part 1 of 3)[a]":"Journey's End (1985)(Games Workshop)(Part 1 of 3)[a]", 
"Journey's End (1985)(Mastertronic)(Part 2 of 3)":"Journey's End (1985)(Games Workshop)(Part 2 of 3)", 
"Journey's End (1985)(Mastertronic)(Part 2 of 3)":"Journey's End (1985)(Games Workshop)(Part 2 of 3)", 
"Journey's End (1985)(Mastertronic)(Part 2 of 3)[a]":"Journey's End (1985)(Games Workshop)(Part 2 of 3)[a]", 
"Journey's End (1985)(Mastertronic)(Part 3 of 3)":"Journey's End (1985)(Games Workshop)(Part 3 of 3)", 
"Journey's End (1985)(Mastertronic)(Part 3 of 3)":"Journey's End (1985)(Games Workshop)(Part 3 of 3)", 
"Journey's End (1985)(Mastertronic)(Part 3 of 3)[a]":"Journey's End (1985)(Games Workshop)(Part 3 of 3)[a]", 
"Kaboom! (1986)(Proxima Software)": "Kaboom! (1986)(Fuxoft)",
"Kong (19xx)(Stephen Hall - Nicholas Walmsley)": "King Kong (19xx)(Nicholas Walmsley)",
"Kung Fu Knights (1989)(Firebird Software)[a][re-release]": "Kung Fu Knights (1989)(Top Ten Software)[a][re-release]",
"Kung Fu Knights (1989)(Firebird Software)[re-release]": "Kung Fu Knights (1989)(Top Ten Software)[re-release]",
"Labirintus (1985)(Tivadar Radacsy)(hu)": "Labirintus (1985)(Laszlo Nyitrai)(hu)",
"Labirintus (1985)(Tivadar Radacsy)(hu)[a]": "Labirintus (1985)(Laszlo Nyitrai)(hu)[a]",
"Labirynt (1988)(Bajtek 6 88 - P.Sz)(pl)": "Labirynt (1988)(Bajtek)(pl)",
"Lange Rueckkehr, Die (1984)(Odyssee)(de)[aka Long Way Home Volume 1]": "Long Way Home Volume 1 (1984)(Odyssee)(de)[aka Long Way Home Volume 1]",
"Mad Martha (1984)(Saturn Development)(es)[re-release]": "Mad Martha (1984)(Mikro-Gen Ltd)(es)[re-release]",
"Madhatter (1985)(Automata UK)": "Madhatter (1985)(Gamma Software)", 
"Magische, Das (19xx)(Juergen Schroth - Georg Trietsch)(de)": "Magische, Das (19xx)(Georg Trietsch)(de)",
"Main Blow, The (1994)(Chip - Rocky)(ru)[128K]": "Main Blow, The (1994)(Inforcom)(ru)[128K]",
"Map Snatch (1985)(Dinamic Software)(es)": "Mapsnatch (1985)(Dinamic Software)(es)",
"Master Chess (1983)(Sinclair Research)(GB)": "Masterchess (1983)(Sinclair Research)(GB)",
"Mega Tron (1993)(Wizard Software)[h FFC Computers - Softstar]": "Mega Tron (1993)(Dominic J. Morris)[h FFC Computers - Softstar]",
"Microbowl (1992)(Gabi Soft)(es)": "Microbowl (1992)(MicroHobby)(es)",
"Midnigth (1989)(Wazertown Works)(es)": "Midnight (1989)(Wazertown Works)(es)",
"Mind Fighter (1988)(Abstract Concepts)": "Mindfighter (1988)(Abstract Concepts)",
"Missile Ground Zero (1989)(Virgin Mastertronic)": "Missile Ground Zero (1989)(Software Creations)",
"Moscow-Paris (1987)(Marck Kiszakicwicz - Jacek Mering)(pl)": "Moscow-Paris (1987)(Jacek Mering)(pl)",
"Mr. Gas (1990)(Dro Soft)(es)": "Mr. Gas (1990)(Xortrapa Soft)(es)",
"Mr. Gas (1990)(Dro Soft)(es)[a2]": "Mr. Gas (1990)(Xortrapa Soft)(es)[a2]",
"Mr. Gas (1990)(Dro Soft)(es)[a]": "Mr. Gas (1990)(Xortrapa Soft)(es)[a]",
"Mr. Gas (1990)(Dro Soft)(es)[h Fatality][t]": "Mr. Gas (1990)(Xortrapa Soft)(es)[h Fatality][t]",
"Na Balkanu Nista Novo (1989)(Samir Ribic - Zeljko Juric)(bs)": "Na Balkanu Nista Novo (1989)(Samir Ribic)(bs)",
"Neptune's Caverns (1994)(Steve Rodgers - Marcus Milton)": "Neptune's Caverns (1994)(Steve Rodgers)",
"Nicotine Nightmare (1985)(Atlantis Software)": "Nicotine Nightmare (1985)(Atlantis Gold)",
"Noah (1990)(Michael Young)": "Noah (1990)(Mike Young)",
"Noughts & Crosses (1997)(JA Software)": "Noughts and Crosses (1997)(Roger Aron)",
"Obliterator (1989)(Melbourne House - Psygnosis)[3593]": "Obliterator (1989)(Melbourne House)[3593]",
"Opposotion (1984)(Pulsonic)": "Opposition (1984)(Pulsonic)",
"Orc Island (1984)(Double Play Adventures)": "Orc Island (1984)(C. Malin)",
"Out Cast (1987)(CRL Group)": "Outcast (1987)(CRL Group PLC)",
"Panama Joe (1984)(Parker Software - Sinclair Research)": "Panama Joe (1984)(Parker Software)",
"Panama Joe (1984)(Parker Software - Sinclair Research)[cr]": "Panama Joe (1984)(Parker Software)[cr]",
"Paranoia (1986)(J. Sanz)(es)": "Paranoia (1986)(Juan Sanz)(es)",
"Path Finder (1983)(Widgit Software)": "Pathfinder (1983)(Widgit Software Ltd)",
"Phantomas en la Luna (1992)(Loko Soft)(es)": "Phantomas en la Luna (1992)(LOKOsoft)(es)",
"Phasorchase (1984)(Anik Microsystems)": "Phasorchase (1984)(Soft Hits)",
"Pick-Pocket (1983)(Gemini Marketing)[16K]": "Pick-Pocket (1983)(Irwan Owen)[16K]",
"Piggy (1985)(Argus Press Software)": "Piggy (1985)(Spectrum Computing)",
"Poc Man (1983)(Programmi Italiani)(it)[16K][aka Gobble a Ghost]": "Gobble a Ghost (1983)(CDS Microsystems)(it)[16K][aka Gobble a Ghost]",
"Prince of Persia (1995)(MC Software)(ru)[h Phantasy][t]": "Prince of Persia (1995)(Magic Soft [2])(ru)[h Phantasy][t]",
"Prison Camp (1985)(Tir - Capsoft)(nl)": "Prison Camp (1985)(Capsoft)(nl)",
"Prohibition (1987)(Zafiro Software Division)[re-release]": "Prohibition (1987)(Zafi Chip)[re-release]",
"QBert (1984)(Parker Software)(GB)(proto)[unreleased]": "Q*Bert (1984)(Parker Software)(GB)(proto)[unreleased]",
"Reactor (1984)(Gemini Marketing)": "Reactor (1984)(Michael Wood)",
"Return of the Jedi - Death Star Battle (1984)(Parker Software - Sinclair Research)": "Return of the Jedi: Death Star Battle (1984)(Parker Software)",
"Return of the Jedi - Death Star Battle (1984)(Parker Software - Sinclair Research)[a]": "Return of the Jedi: Death Star Battle (1984)(Parker Software)[a]",
"Return of The Jedi - Death Star Battle (1984)(Parker Software)(GB)(proto)": "Return of the Jedi: Death Star Battle (1984)(Parker Software)(GB)(proto)",
"Ring of Darkness, The (1983)(Wintersoft)(Side A)(Start Side)": "Ring of Darkness, The (1983)(John F. Humphreys)(Side A)(Start Side)",
"Ring of Darkness, The (1983)(Wintersoft)[b][load 1 of 6]": "Ring of Darkness, The (1983)(John F. Humphreys)[b][load 1 of 6]",
"Ring of Darkness, The (1983)(Wintersoft)[b][load 2 of 6]": "Ring of Darkness, The (1983)(John F. Humphreys)[b][load 2 of 6]",
"Ring of Darkness, The (1983)(Wintersoft)[b][load 4 of 6]": "Ring of Darkness, The (1983)(John F. Humphreys)[b][load 4 of 6]",
"Ring of Darkness, The (1983)(Wintersoft)[b][load 6 of 6]": "Ring of Darkness, The (1983)(John F. Humphreys)[b][load 6 of 6]",
"Road Wars (1987)(Melbourne House)": "Roadwars (1987)(Melbourne House)",
"Scrabble DeLuxe (1987)(Virgin Games)": "Scrabble DeLuxe (1987)(Leisure Genius)",
"Self Destruct (1985)(Atlantis Software)": "Self Destruct (1985)(Atlantis Gold)",
"Sex Game (19xx)(Softlake - Meastrosoft)": "Sex Game (19xx)(Meastrosoft)",
"Sim City (1989)(Maxis Software)": "Sim City (1989)(Infogrames)",
"Sinclair ZX Spectrum Test ROM (1983)(Sinclair Research)(GB)[unpublished]": "Sinclair ZX Spectrum Test ROM (1983)(Ian Logan)(GB)[unpublished]",
"Sir Fred (1986)(Zigurat Software)(es)": "Sir Fred (1986)(Made in Spain)(es)",
"Strike Force Cobra (1986)(Zafiro Software Division)[re-release]": "Strike Force Cobra (1986)(Zafi Chip)[re-release]",
"Strip Jack (1984)(J. Weigner - M. Reimann)(de)": "Strip Jack (1984)(J. Weigner)(de)",
"Strip Jack (1984)(J. Weigner - M. Reimann)(de)[a]": "Strip Jack (1984)(J. Weigner)(de)[a]",
"Super Nova (1987)(Players Software)": "Supernova (1987)(Players Software)",
"Time Trax (1986)(Bug-Byte Software)[re-release]": "Timetrax (1986)(Bug-Byte Software)[re-release]",
"Time Trax (1986)(Mind Games Espana)[re-release]": "Timetrax (1986)(Mind Games Espana)[re-release]",
"Time Trax (1986)(Mind Games)": "Timetrax (1986)(Mind Games)",
"Time Trax (1986)(Mind Games)[cr Bill Gilbert]": "Timetrax (1986)(Mind Games)[cr Bill Gilbert]",
"Trail Racer (1987)(Jorgen Bech)": "TrailRacer (1987)(Jorgen Bech)",
"Trans-Europa B.V. (1984)(Wolters Software)(nl)[aka Car Journey]": "Trans-Europa BV (1984)(Wolters Software)(nl)[aka Car Journey]",
"Typhoon (1988)(Ocean)": "Typhoon (1988)(Imagine Software Ltd)",
"Typhoon (1988)(Ocean)[128K]": "Typhoon (1988)(Imagine Software Ltd)[128K]",
"Typhoon (1988)(Ocean)[a2][128K]": "Typhoon (1988)(Imagine Software Ltd)[a2][128K]",
"Typhoon (1988)(Ocean)[a]": "Typhoon (1988)(Imagine Software Ltd)",
"Typhoon (1988)(Ocean)[a][128K]": "Typhoon (1988)(Imagine Software Ltd)[a][128K]",
"Typhoon (1988)(Ocean)[h Fatality][t]": "Typhoon (1988)(Imagine Software Ltd)[h Fatality][t]",
"Typhoon (1988)(Ocean)[h]": "Typhoon (1988)(Imagine Software Ltd)[h]",
"U-Boat Hunt (1983)(Protek Computing)": "U-Boat Hunt (1983)(Rod K. Hopkins)",
"Videostop (19xx)(Video Stop Games)(cs)": "Videostop (19xx)(CV Software)(cs)",
"Who Dunnit (1984)(CCS)": "Whodunnit? (1984)(CCS)",
"Wonderboy (1987)(Activision)": "Wonder Boy (1987)(Activision)",
"Xreversy (demo) (1997)(XL-Design)": "Xreversy (demo) (1997)(Creator)",
"Z-Fred (1984)(AK Wood)": "Z-Fred (1984)(Popular Computing Weekly)",
"Z-Fred (1984)(AK Wood)[different font]": "Z-Fred (1984)(Popular Computing Weekly)[different font]",

};

var publisher = {
"A & F Software": "A'n'F Software",
"A. Biglin": "Andrew Biglin",
"A. Makushkin - M. Demyanko": "A. Makushin",
"A.C.E. Software": "A.C.E. [3]",
"Aardwark Software": "Aardvark Software of Hartlepool",
"ABC Analog": "ABC Soft",
"ACS Software": "Alexander Computing Systems",
"Activision": "Activision Inc",
"Ad. Lomer": "Ad Lomer",
"Alexander Belousov": "Aleksandr Belousov",
"Amador, Javier": "Javier Amador",
"Amazon Software": "Amazon Systems",
"Art Work Creative Group": "Artwork",
"Avalon Software": "Avalon",
"B. Lutz": "Bernhard Lutz",
"Bat Soft": "Batsoft",
"Belltons Informatica - Paraninfo Soft": "Belltons Informatica",
"Benkosoft": "Ivan Benishek",
"Boss Software": "B.O.S. Software",
"Bothers": "Brothers",
"Bubblebus Software": "Bubble Bus Software",
"Caubet, Josep Coletas": "Josep Coletas Caubet",
"Cheetasoft": "CheetahSoft Ltd",
"Chiaverano, Mariano E.M.": "Mariano E.M. Chiaverano",
"Clevers Group - Triumph": "Clevers Group",
"CLR Group": "CRL Group PLC",
"Codemasters Gold": "Code Masters Gold",
"Codemasters Plus": "Code Masters Plus",
"Codemasters": "Code Masters Ltd",
"Coletas Caubet, Josep": "Josep Coletas Caubet",
"Costa, Rafael Vico": "Rafael Vico Costa",
"Create Soft Research": "Create Soft",
"Cubeckin Vitaliy": "Vitaly Kubeckin",
"Cyber Punks Universal": "CyberPunks Unity",
"DACC": "D.A.C.C. Ltd",
"Dan B. Nielsen": "Dan Brochner Nielsen",
"Data Masters Software": "Datamasters Software",
"David Ashton - Grant Wilson": "David Ashton",
"Dimiksoft - SSA": "Dimiksoft",
"DK'Tronics": "DK'Tronics Ltd",
"Dominic Morris": "Dominic J. Morris",
"E.F.S. Production": "Excellent Four Software",
"Erbe Software - Ocean": "Erbe Software S.A.",
"Eurobyte": "Euro-Byte Ltd ",
"F. Oliver": "Frank Oliver",
"Fahrenheit 3000 (1985)(Silverbird Software)":"Fahrenheit 3000 (1985)(Silverbird Software)", 
"Fahrenheit 3000 (1985)(Silverbird Software)":"Fahrenheit 3000 (1985)(Silverbird Software)", 
"Fahrenheit 3000 (1985)(Silverbird Software)[a]":"Fahrenheit 3000 (1985)(Silverbird Software)[a]", 
"Federico Alvarez Valero": "Federico J. Alvarez Valero",
"Fiedrich Zohmann": "Friedrich Zohmann",
"Frebird": "Firebird Software Ltd",
"Fuxsoft": "Fuxoft",
"G. Owen": "Garry Owen",
"G. Whitehead": "Gary Whitehead",
"Gadtek Games - Sinclair User": "Gadtek Games",
"Game Busters": "Gamebusters",
"Gandarillas, Carlos": "Carlos Gandarillas",
"Garcia, Aitor Gomez": "Aitor Gomez Garcia",
"Gemini Marketing": "Gemini Software",
"George Calvere": "George",
"Graig Communications": "Craig Communications Ltd",
"Green Bit Group": "Green Bit",
"Green Fish Software Enterprises": "Green Fish Software Enterprise",
"H-PRG": "Hooy-Program",
"H.D.S.": "Hackerz' Design Software",
"Hackers Design Software":"Hackerz' Design Software",
"Harold Gale Software": "Harold Gale Associates Ltd",
"Heinemann - Hill MacGibbon": "Heinemann,",
"Impressions Software": "Impressions Ltd",
"Interceptor Micros Software": "Interceptor Software",
"J. Theakston - S. Richards": "J. Theakston",
"J.J.K. Research": "JJK Research Limited",
"JA Software": "J. Aron Software Ltd",
"Jeroen Kwast": "Jeroen J. Kwast",
"Jioi Chabek": "Jiri Chabek",
"Jokersoft": "Jocker Soft",
"Jorge, Lucas": "Lucas Jorge",
"KAW": "Krajowa Agencja Wydawnicza",
"KMP Soft": "KHP Soft",
"Kobrahsoft Software": "Kobrahsoft",
"Linel Software": "Linel",
"Loko Soft": "LOKOsoft",
"Luis F. Sanchez": "Luis Felipe Sanchez Palacios",
"Luis Sanchez Palacios": "Luis Felipe Sanchez Palacios",
"M. Pilia": "Massimo Pilia",
"M.K. Circuits": "M.K.",
"M.V. Spiridonenko":"Spiridonenko MV",
"Macmillan Software - Sinclair Research": "Macmillan Software Ltd",
"MAJA Software - CID Software": "CIDsoft",
"Master Games": "Masters Games",
"MC Software": "Magic Soft [2]",
"Michael Silverberg": "Michael Silberberg",
"Microstyle": "Micro Style",
"Mixt Software": "Mixt Dimension",
"Mr Bleeper - Slavik - Mast - Midi": "Last Masters Group",
"N-Discovery": "n-Discovery",
"Nebula Design Software": "Nebula Designs Software",
"Nieto, Eduardo Mena": "Eduardo Mena Nieto",
"Nikola Alivojvodic": "Alivojvodic Nikola",
"Oleg Moskalenko": "Oleg Moscalenco",
"Origin Software": "Origin Systems Inc",
"PancSoft": "Panc Software",
"Pelaez, Lucas": "Lucas Pelaez",
"Peter Curtis": "Peter G. Curtis",
"Phips Associates": "Phipps Associates",
"Pick 'n' Choose": "Pick & Choose",
"Piper Books": "Piper Software",
"Players Premier Software": "Players Premier",
"Players Software - Sinclair User": "Sinclair User",
"Power Software": "Power",
"Power Software": "PowerSoftware",
"Prospek Computing Cooperation": "Prospec",
"Rage Tech. - Arny": "Rage Technologies",
"Relax Games": "Reelax Games",
"Richard Shepard Software": "Richard Shepherd Software Ltd",
"Rock & Soft": "Rock'n'Soft",
"Roland G. Huelsmann": "Roland G. Hulsmann",
"Romanic Warriors": "Romantic Warriors",
"Ross, Fraser": "Fraser Ross",
"S. Davis": "Steven Davis",
"S.V. Kukoviakin": "S. Kukoviakin",
"Sacred Scrolls Software": "Sacred Scroll Software",
"Scorpio Software": "Scorpio Gamesworld Ltd",
"Shadow Software": "Shadow Soft",
"Silicon Brains Group": "Silicon Brains Software Ltd",
"Simon & Julia Barnsley": "Simon Barnsley",
"Sir Clive - Mr ZX": "Sir Clive and Mr ZX",
"Smokers Hackers Group": "Smokers",
"Softek Software International": "Softek",
"Softel Software": "Softel",
"Software Super Savers": "Software Supersavers Ltd",
"Spectrum Adventure Exch Club": "Spectrum Adventure Exchange Club",
"Stankinsoft": "Stankisoft",
"Statesoft": "State Soft Ltd",
"Sunny Team": "Sunny Tram",
"T. Tang": "Tat Tang",
"The Edge Software": "The Edge",
"The Ramjam Corporation": "The RamJam Corporation",
"Time Assasin": "Time Assassin",
"Tm'M Studio": "TM'M Studio",
"Topo Soft - Ocean": "Topo Soft",
"Triebkraft - 4th Dimension": "Triebkraft",
"TSB Magic Micro Club": "TSB",
"TSS": "The Smart Soft",
"U.S. Gold": "US Gold Ltd",
"Ultrasoft - Sintech": "Ultrasoft [2]",
"USW": "U.S.W.",
"Vincent & Peter Li": "Peter Li",
"Virgin Mastertronic": "Virgin Mastertronic Ltd",
"WE Group": "WE [Belarus]",
"Wintersoft": "Winters Ltd",
"Wizard Software": "Wizard Computer Games",
"Yunior Soft - TK": "Yunior Soft",
};

module.exports = {
    gamename: gamename,
    publisher: publisher
}
