var missing = [
"128 Colour (19xx)(-)",
"1D Tetris (1998)(CSSCGC)",
"21 (1993)(A. Evdokimov)(ru)",
"2D Mini Maze (1996)(CSSCGC)",
"3-D Golf (19xx)(-)(de)",
"3-D Noughts and Crosses (1982)(Machinecroft)",
"3-D Tic-Tac-Toe (1983)(Ansgar Zerfass)(de)", 
"3D Labyrinth (19xx)(-)",
"3D Labyrinth (19xx)(-)(de)",
"3D Labyrinth (19xx)(-)[a]",
"3D Maze (1996)(CSSCGC)",
"3D Tennis (19xx)(-)",
"3D Tennis (19xx)(-)[a2]",
"3D Tennis (19xx)(-)[a3]",
"3D Tennis (19xx)(-)[a]",
"3D Word (1983)(P. Monger)", 
"3D-Labyrinth (1983)(-)(de)",
"500 Millas Indianapolis (19xx)(-)(es)[16K]",
"A Day in the Life of Arnold (1996)(CSSCGC)",
"A Day in the Life of Arnold (1996)(CSSCGC)",
"A Day in the Life of Arnold (1996)(CSSCGC)[a2]",
"A Day in the Life of Arnold (1996)(CSSCGC)[a2]",
"A Day in the Life of Arnold (1996)(CSSCGC)[a]",
"A Day in the Life of Arnold (1996)(CSSCGC)[a]",
"A Day in the Life of Mike the Mole (1999)(CSSCGC)",
"A To Snad Ne! (19xx)(-)(cs)(Part 1 of 2)[128K]",
"A To Snad Ne! (19xx)(-)(cs)(Part 2 of 2)[128K]",
"Aberdeen (1999)(CSSCGC)",
"Ad Lister (19xx)(-)",
"Advanced Advocacy Simulator (1997)(CSSCGC)",
"Advanced Advocacy Simulator (1997)(CSSCGC)",
"Advanced Binary Simulator (1998)(CSSCGC)",
"Advanced Binary Simulator (1998)(CSSCGC)",
"Advanced Coin Simulator (19xx)(Codehamsters)",
"Advanced Death Simulator (1998)(CSSCGC)",
"Advanced Death Simulator (1998)(CSSCGC)",
"Advanced Nether Earth (1998)(Eternity Industry)(ru)",
"Advanced Pro Wife Simulator (1999)(CSSCGC)",
"Advanced Pro Wife Simulator (1999)(CSSCGC)",
"Advanced Road Rage Simulator (1997)(CSSCGC)",
"Advanced Road Rage Simulator (1997)(CSSCGC)",
"Advanced W-nking Simulator (1998)(CSSCGC)",
"Advanced W-nking Simulator (1998)(CSSCGC)",
"Advanced Wallpaper Simulator (1998)(CSSCGC)",
"Advanced Wallpaper Simulator (1998)(CSSCGC)",
"Advanced Year 2000 Simulator (1999)(Rob Erlich)[128K]", "100 km Race (19xx)(Coyote Software)",
"Adventure in Bristol (1996)(CSSCGC)",
"Adventure Lister (19xx)(-)",
"Adventure Tutor (19xx)(-)",
"Air Fire (19xx)(Rebit Soft Bank)(it)",
"Alaska (19xx)(-)(de)",
"Alchemist Puzzle (1995)(Vaxalon)", 
"Alien Chase (19xx)(-)[16K]",
"Alien Death Mine Massacre XII (1997)(CSSCGC)",
"Alkash (2002)(Ellipse)(ru)",
"Allo Call (19xx)(-)",
"Almanac (19xx)(-)",
"Amazing Voyage (1984)(-)",
"Andeskydning (19xx)(-)(da)",
"Andrew's (1997)(CSSCGC)",
"Android Nim (19xx)(-)",
"Andromeda (1983)(PSS)",
"Andromeda (1983)(PSS)[a]",
"Andromeda 3 (19xx)(-)",
"Andromeda Chess (1984)(Andromeda)",
"Andromeda Chess (1984)(Andromeda)[a]",
"Ant KO (19xx)(-)(el)[16K]",
"Anthea Turner's National Lottery Simulator (1996)(CSSCGC)",
"Apple Catcher (2002)(Naffsoft)", 
"Arbatax (19xx)(-)(de)",
"Arcade Machine Test Failure Emulator (1999)(CSSCGC)",
"Arcade Volleyball (1997)(Romer's Software)(ru)",
"Arcade Volleyball (demo) (1995)(Warlocks)",
"Arkanods (19xx)(-)",
"Arkanods (19xx)(-)[a2]",
"Arkanods (19xx)(-)[a]",
"Arklay FC (1999)(CSSCGC)",
"Asocijacije (1998)(Nikola Alivojvodic)(sr)",
"Asteroids (1983)(P.S. Newby)", 
"Astral Invasion (1982)(Astral Software)[16K]",
"Ataque Alienigena (19xx)(-)(es)[16K]",
"Aterrizaje (19xx)(-)(es)[16K]",
"Athelete (1984)(Buffer Micro)",
"Atrapada (19xx)(-)(es)[16K]",
"Aurascope (1992)(Zenobi Software)",
"Aurascope (1992)(Zenobi Software)[128K]",
"Aventura (1989)(-)(es)",
"Aventura (19xx)(-)(es)",
"Aventuras em Serra Pelada (19xx)(Metalsoft)(pt)", 
"Aventuras na Selva (19xx)(Metalsoft)(pt)", 
"Awari (1984)(Orbis Publishing)[a2][16K]", 
"Back 9, The (19xx)(-)",
"Back 9, The (19xx)(-)[a]",
"Bala (19xx)(-)(es)[16K]",
"Ballenas (19xx)(-)(es)[16K]",
"Balloon (1997)(CSSCGC)",
"Base (1992)(Inforkom)", 
"Bash 'n' Grab (1997)(CSSCGC)",
"Batalla EN (1983)(Joaquin Fuster)(es)[16K]", 
"Batspil (19xx)(-)(sv)",
"Battleships (1984)(Interface Publications)[16K]",
"Bearings (19xx)(-)",
"Belagerung (19xx)(-)(de)[16K]",
"Benny Bunny - Firefighter (19xx)(-)",
"Benny Bunny - Firefighter (19xx)(-)[a]",
"Benny Bunny - Gold Rush (19xx)(-)",
"Benny Bunny - Gold Rush (19xx)(-)[a]",
"Benny Bunny - Haunted Belltower (19xx)(-)",
"Benny Bunny - Haunted Belltower (19xx)(-)[a]",
"Benny Bunny - Monster Mansion (19xx)(-)",
"Benny Bunny - Monster Mansion (19xx)(-)[a]",
"Bentley Bear (19xx)(-)",
"Bentley Bear (19xx)(-)[a]",
"Bergwacht (19xx)(-)(de)",
"Bertie Bug (19xx)(-)",
"Best Thing Since Sliced Bread, The (1998)(CSSCGC)",
"Big Railway Adventure (19xx)(Mark Gipson)", 
"Bingo (1983)(Taller de Aplicaciones Informaticas)(es)",
"Bingo (1983)(Taller de Aplicaciones Informaticas)(es)[a]", 
"Bingo (19xx)(-)",
"Bismarck (19xx)(-)(es)",
"Bitva o Britanii (1984)(Lada)(cs)[aka Battle of Britain]",
"Bitwa o Wyspe II (19xx)(-)",
"Bitwa o Wyspe II (19xx)(-)(cs)",
"Bitwa o Wyspe II (19xx)(-)(cs)[a2]",
"Bitwa o Wyspe II (19xx)(-)(cs)[a]",
"Black Jack (19xx)(-)",
"Black Raven - Start Up Manager v1.01b (19xx)(-)(ru)",
"Blackjack (1984)(Oxford Computer Publishing)", 
"Blitz (1997)(CSSCGC)",
"Blitz (19xx)(-)",
"Block Tetris (1994)(Dimik Soft)(ru)", 
"Bludisko (1997)(CSSCGC)",
"Bobsleigh (19xx)(-)(es)",
"Boby (1990)(Pilot Soft - Matysoft)(cs)",
"Boing Plop (1997)(CSSCGC)",
"Bolos (19xx)(-)(es)[16K]",
"Bomba (19xx)(-)(hu)[16K]",
"Bombazo (1996)(Laszlo Nyitrai)(hu)[128K]", 
"Bonweshar Uctopur (1994)(Fantasy)(ru)[128K]", 
"Bor-Fies (1985)(Soft Well)(it)[a][aka Bug-Eyes]", 
"Bor-Fies (1985)(Soft Well)(it)[aka Bug-Eyes]",
"Bosque (19xx)(-)(es)",
"Boulder Dash V (1992)(Too Trek Moscow S.N.G.)",
"Boulder Dash VI (1992)(Too Trek Moscow S.N.G.)",
"Brainwaves (19xx)(-)",
"Breakout (1997)(CSSCGC)",
"Bug Boot (1999)(Bugsy)", 
"Build That Tower (1996)(CSSCGC)",
"Bullseye (1997)(CSSCGC)",
"Buriabeast (1984)(-)",
"Burp-Man (1996)(CSSCGC)",
"Business Demo (19xx)(-)",
"Byegstvo na Harhan (1998)(Air)(ru)[h Dr. Dash]", 
"Byelyj Oryel - Tovaritch Izvyestyen (1998)(Fatality)(ru)", 
"Calipse (19xx)(-)",
"Cantona Football (1996)(CSSCGC)",
"Cards (19xx)(-)",
"Carreras (19xx)(-)(es)[16K]",
"Cartridge Code (19xx)(-)",
"Castillo Encantado (19xx)(-)(es)",
"Castle (1996)(CSSCGC)",
"Castle (19xx)(-)",
"Cat + Mouse (1996)(CCSCGC)", 
"Catchy (1984)(Eric Verlind)", 
"Catchy (1984)(Eric Verlind)[a]", 
"Cave-Fighter (19xx)(-)(de)[16K]",
"Caves of Mondonia (1988)(CSSCGC)",
"Cell of the Ridges (19xx)(-)",
"Champs (1983)(Peaksoft)",
"Chamurabi (19xx)(-)(cs)",
"Chaos - The Battle of the Wizards - Editor (1985)(Emulate)", 
"Chaos - The Battle of the Wizards - Editor (1985)(Emulate)[a]", 
"Chart Topper (19xx)(-)",
"Chart Topper (19xx)(-)[a]",
"Cheese Magnate (1998)(CSSCGC)[128K]",
"Chess (1996)(CSSCGC)",
"Chicago (19xx)(-)(de)",
"Chicago Gang (1984)(Scanner Productions)(es)", 
"Chip (19xx)(-)(es)",
"Chop Lifter (19xx)(-)",
"Chronos 128k Remix (1991)(Gremlin Graphics Software)[h Avalon]",
"Cifromaniya (1998)(Area Soft)(ru)", 
"Cir$a (19xx)(Jordi Sales)(es)", 
"City Bomber (1997)(CSSCGC)",
"City Bomber (1997)(CSSCGC)[a2]",
"City Bomber (1997)(CSSCGC)[a]",
"City Defender (1983)(Vaba Software)(it)[16K][aka Missile Defence]",
"Clifftop View (1999)(CSSCGC)",
"Clifftop View (1999)(CSSCGC)[a]",
"Clutches of the Balrog (19xx)(-)",
"Coin Game (19xx)(Ceran Software)(de)[16K]",
"Color Lines (1996)(Computer Works Company)(ru)",
"Color Lines (19xx)(-)",
"Come Come Come Come (1983)(Monser)(es)[aka Munch Man]", 
"Comecocos (19xx)(-)(es)",
"Comipini (19xx)(-)(es)",
"Connect 3 (1999)(Andrew Collier)", 
"Connect 4 (19xx)(-)",
"Copas (19xx)(-)(es)[16K]",
"Copfm 3 (19xx)(-)",
"Cosa, La (1988)(-)[h Omega Hackers Group]",
"Crush Up (1984)(ZXS)(de)", 
"Crush Up (1984)(ZXS)(de)[a]", 
"Curse of the Sandwitch (1999)(CSSCGC)",
"Daleks (1997)(CSSCGC)",
"Dama (19xx)(-)(ru)",
"Damas Rev (19xx)(-)(es)",
"Dame (19xx)(-)(de)[16K]",
"Dame (19xx)(-)[16K]",
"Dammen (1984)(Book)(nl)",
"Dark Room Simulator (1996)(CSSCGC)",
"Day Trip (19xx)(-)",
"Defender (1982)(Blaby Computer Games)", 
"Defusion (1986)(Wrench)", 
"Defusion (1986)(Wrench)[a]", 
"Destructor (19xx)(-)(es)[16K]",
"Devils Sceptre (19xx)(-)",
"Diamonds (1986)(Bill Gilbert)", 
"Dice Throw (1995)(Vaxalon)", 
"Dining (19xx)(-)",
"Dizzy CS (1993)(+Gama Software)(cs)", 
"Dodgy's Castle (1999)(CSSCGC)",
"Dog Fight (19xx)(-)",
"Doolhof (1984)(Book)(nl)", // ZX81
"Dracula's Castle (1986)(Artur Marques)(pt)",
"Dracula's Castle (1986)(Artur Marques)(pt)(Part 1 of 3)",
"Dracula's Castle (1986)(Artur Marques)(pt)(Part 2 of 3)",
"Dracula's Castle (1986)(Artur Marques)(pt)(Part 3 of 3)",
"Draughts (1984)(Book)",
"Duggy (19xx)(-)(de)",
"Dummy (1985)(Elite Systems)", 
"Dustin 128 (1988)(Hewson Consultants)[h Ascendancy][re-release]",
"Dyke (1996)(CSSCGC)",
"Earthbound (1984)(Central Solutions)", 
"Earthbound (1984)(Central Solutions)", 
"Earthbound (1984)(Central Solutions)[a]", 
"Ego (1997)(CSSCGC)",
"Egyptian Pyramid (19xx)(-)(de)",
"Egyptian Pyramid (19xx)(-)(de)[a]",
"Eight Cards Patience (19xx)(-)",
"Einstein (1996)(CSSCGC)",
"Emulator Speed Test (19xx)(-)",
"End of the World Simulator (1999)(CSSCGC)",
"Energy Fields (19xx)(-)",
"Enforcer 1 (1999)(CSSCGC)",
"Enforcer 1 (1999)(CSSCGC)[a]",
"Enforcer 2 (1999)(CSSCGC)",
"Enforcer 2 (1999)(CSSCGC)",
"English to Giant Translator (1999)(CSSCGC)",
"Enterprise (19xx)(-)(de)",
"Enterprise (19xx)(-)[h Step Creative Group]",
"Escape from Malagar (19xx)(-)",
"Escape from Malagar (19xx)(-)[a]",
"Escape to Eskolos (1987)(Gilsoft International)", 
"Escape! (1997)(CSSCGC)",
"Fantastic Adventure (1999)(CSSCGC)",
"Fantastic Mission (1984)(Program Software)(es)", 
"Fantastic Mission (1984)(Program Software)(es)[a]", 
"Fantasy Zone 2, The (19xx)(-)[128K]",
"Fantasy Zone 2, The (19xx)(-)[128K][Multiface copy]",
"Festung (19xx)(-)(de)",
"Filler (1996)(CSSCGC)",
"Fisher (demo) (1997)(I.M.A. Production)(ru)", 
"Five Dice (1985)(Paxman Promotions)[re-release]", 
"Fiveteen's (1996)(Greedy Guys Group)", 
"Fiveteen's (1996)(Greedy Guys Group)[t]", 
"Fiveteen's v1.0 (1996)(A.Vashin)", 
"Flying Dragons (1986)(Special Program)[h Oldman][t][aka Thanatos]",
"Football Manager (19xx)(-)",
"Forgotten Village, The (1999)(CSSCGC)",
"Forgotten Village, The (1999)(CSSCGC)",
"Four Row's Pasyance (1997)(Amazing Software Making)(ru)", 
"Four Row's Pasyance (1997)(Amazing Software Making)(ru)", 
"Fransk (19xx)(-)(da)",
"Frere Gustav (1995)(Vaxalon)", 
"Frog (19xx)(-)",
"Froglets (1984)(Cascade Games)(de)[16K]",
"Froglets (1984)(Cascade Games)(sr)[16K]",
"Froglets (1984)(Cascade Games)[16K]",
"Froglets (1984)(Cascade Games)[a][16K]",
"Frosch (19xx)(-)(de)",
"Fruit (1997)(CSSCGC)",
"Fruit Machine (19xx)(-)",
"Fruitmachine (1985)(Firebird Software)", 
"Fruitmachine (1985)(Firebird Software)[a]", 
"Fussball (1986)(Klaus Jahn)(de)", 
"Gablota (19xx)(-)(pl)",
"Galgje (19xx)(-)(nl)",
"Galipoli (1986)(CCS)",
"Galipoli (1986)(CCS)[128K]",
"Gamao (1983)(-)(pt)",
"Get That Emulator (1997)(CSSCGC)",
"Ghosts (1997)(CSSCGC)",
"Gold Fever (1996)(-)(ru)",
"Golf (19xx)(-)(es)",
"Gran Juego de Inteligencia (19xx)(-)(es)",
"Greg the Egg (19xx)(-)(Side A)[unpublished]",
"Greg the Egg (19xx)(-)(Side B)[unpublished]",
"Ground Strike (1997)(CSSCGC)",
"Guideline (1983)(-)",
"Hangman (1996)(CSSCGC)",
"Hangman (19xx)(-)[16K]",
"Happelaar - Spacman (19xx)(-)(nl)[16K]",
"Haus des Wahnsinns, Das (1983)(Christof Buening)(de)[16K]",
"Haushaltsbuchfuehrung (19xx)(-)(de)",
"Heavyweight (19xx)(-)[16K]",
"Heilige Rustung des Antiriad, Die (1986)(-)(de)[a][aka Sacred Armour of Antiriad, The]",
"Heilige Rustung des Antiriad, Die (1986)(-)(de)[aka Sacred Armour of Antiriad, The]",
"Heli-Land (19xx)(-)(de)[16K]",
"Helikopter (19xx)(-)(de)[16K]",
"Hi Lo (19xx)(-)",
"Hi Lo (19xx)(-)[a]",
"Hi-Lo (19xx)(-)",
"Hi-Lo (19xx)(-)[a]",
"Hockey (1997)(CSSCGC)",
"Hoellensturz (19xx)(-)(de)",
"Honest Joe (1999)(CSSCGC)",
"Honest Joe (1999)(CSSCGC)",
"Horace Goes Seal Culling (1997)(CSSCGC)",
"House of Horrors (19xx)(-)[16K]",
"Hunchback 84 (1999)(CSSCGC)",
"Hunchy (19xx)(-)",
"Hunter (1991)(Atlantis Software)",
"Hunter (1991)(Atlantis Software)[h World Eyes Group][t]",
"Hunter (19xx)(-)",
"Impulse (1983)(-)",
"Invaders (1997)(CSSCGC)",
"Invaders (19xx)(-)(es)",
"Invaders (19xx)(-)(es)",
"Island (1983)(-)",
"Ivan Stupid (1997)(-)(ru)",
"Jackpot (19xx)(-)(de)",
"Jackpot (19xx)(-)(de)[a]",
"Jet Set Willy - Editor (19xx)(-)(de)",
"Jet Set Willy - Willy's New Hat (1985)(-)",
"Jewels of Power (19xx)(-)",
"Joe's Drink Limonaden Stand (19xx)(-)(de)[16K]",
"Jogger (19xx)(-)(de)",
"Jongleur (19xx)(-)(de)",
"Juego del Dragon (19xx)(-)(es)[16K]",
"Jump Frog (19xx)(-)(es)",
"Kingdom (1996)(CSSCGC)",
"Kingdom (19xx)(-)",
"Kleuren Kubus (1984)(Book)(nl)",
"Klingsor the Evil Magician (19xx)(-)",
"Klingsor the Evil Magician (19xx)(-)[a]",
"Kongedomme (19xx)(-)(da)",
"Kongedomme (19xx)(-)(da)[a]",
"Kosci Rzucone (19xx)(-)(pl)",
"Kuzelky (19xx)(-)(cs)",
"Labirint (1983)(Darko - Vlado)(hr)[aka 3D Maze]",
"Labirinto 3D (1984)(Programmi Italiani)(it)[16K][aka Labyrinth]",
"Las Vegas II (1991)(-)",
"Las Vegas II (1991)(-)[cr Roby]",
"Laser 11 (19xx)(-)",
"Laser Attack (19xx)(-)(de)[16K]",
"Lemmings - File Editor (19xx)(-)",
"Leopard (19xx)(-)(es)",
"Lift (19xx)(-)(de)",
"Little Batty (1999)(CSSCGC)",
"Looped Loop (19xx)(-)",
"Looped Loop (19xx)(-)[a]",
"Lothlorien (19xx)(-)(es)",
"Loto (19xx)(-)(es)[16K]",
"LSF! (demo) (1994)(-)(ru)",
"Mage Cage (19xx)(-)[16K]",
"Magic Circle, The (19xx)(-)[128K]",
"Magic Circle, The (19xx)(-)[a][128K]",
"Magic Jokers (19xx)(-)",
"Magical Mystery Tour (19xx)(-)",
"Mago, El (19xx)(-)(es)",
"Malice (19xx)(-)",
"Mampfman (19xx)(-)(de)",
"Manager (19xx)(-)(ru)",
"Manor Murder Case, The (19xx)(-)",
"Map Snatch (1985)(Dinamic Software)(es)[h Rapeware]",
"Martian Attack (19xx)(-)",
"Master 4 (19xx)(-)",
"Masterminde (19xx)(-)",
"Maze (1996)(CSSCGC)",
"Maze (19xx)(-)[16K]",
"Maze 2 (1996)(CSSCGC)",
"Maze Change (1997)(CSSCGC)",
"Maze Chase (1997)(CSSCGC)",
"Metal Detector '79 (1997)(CSSCGC)",
"Meteor Mission (19xx)(-)[16K]",
"Meteor Mission (19xx)(-)[a][16K]",
"Miao (1985)(Programmi Italiani)(it)[aka Paws]",
"Micromouse (19xx)(-)",
"Mighty Sword of the Dark, The (1996)(CSSCGC)",
"Mihotabpa (19xx)(-)(ru)",
"Mill (1984)(V.D.G.)",
"Minefield (1997)(CSSCGC)",
"Mines (demo) (1996)(SS)[h Zer0]",
"Minesweeper (1997)(CSSCGC)",
"Missile Defender (19xx)(-)",
"Moggy Murder (1997)(CSSCGC)",
"Monopoli (1984)(Di Rosa & Figlio)(it)[aka Do Not Pass Go]",
"Moon Rescue (19xx)(-)",
"Moon-Cargo (19xx)(-)(de)",
"Mow Business (1999)(CSSCGC)",
"Mr. Blobby Goes Down the Newsagents (1996)(CSSCGC)",
"Mucroid Run (19xx)(-)",
"Nails (1999)(CSSCGC)",
"Nimm (19xx)(-)",
"Not Lords of Midnight (19xx)(-)",
"Noughts and Crosses (1996)(CSSCGC)",
"Nudgeeit (1985)(Automata UK)",
"Number (1997)(CSSCGC)",
"Number One (19xx)(-)",
"Octopus Life (1999)(CSSCGC)",
"Odyssee (19xx)(-)(de)",
"Omega 2 (19xx)(-)",
"One Queen Puzzle, The (1999)(CSSCGC)",
"Open Safe (1999)(-)(ru)",
"Orbit (1996)(CSSCGC)",
"Organ (19xx)(-)",
"Osvajanje Zvedza (19xx)(-)(sr)",
"Othello (19xx)(-)(de)[16K]",
"Outlaws (19xx)(-)",
"Overboard (1996)(CSSCGC)",
"Pac-Man (19xx)(-)",
"Pesadilla (19xx)(-)(es)",
"Pfui Spinne (19xx)(Book)(de)",
"Phoenix (19xx)(ZX Spectrum Club)(it)[16K]",
"Pi Week the Quest (1997)(CSSCGC)",
"Piano (19xx)(-)",
"Ping Pong (1996)(Claus Jahn - Andy Schraepel)(de)",
"Plane Attack (19xx)(-)",
"Planet Fighter (19xx)(-)(de)",
"Play Your Cards Right (1986)(-)[16K]",
"Plus 3 Tennis II (1996)(CSSCGC)",
"Pocker (19xx)(-)(es)",
"Pod (1987)(Mastertronic)",
"Pod (1999)(CSSCGC)",
"Pod (1999)(CSSCGC)",
"Poke Alex in the Eye (1998)(CSSCGC)",
"Poke Alex in the Eye II (1998)(CSSCGC)",
"Poker (1996)(CSSCGC)",
"Poker (19xx)(-)[16K]",
"Pokland (1984)(Proxima Software)(cs)",
"Pongo (1983)(-)",
"Pozar Wiezowca (19xx)(-)(pl)",
"Practice (1997)(CSSCGC)",
"Presidente (19xx)(-)(es)",
"Prinsessen i Berget det Blaa (19xx)(-)(sv)",
"Prinsessen i Berget det Blaa (19xx)(-)(sv)[a]",
"Prison Camp (19xx)(-)",
"Puluc (19xx)(-)(de)",
"Purple Demon (1996)(CSSCGC)",
"Purple Demon 2 (1997)(CSSCGC)",
"Purple Demon 3 (1998)(CSSCGC)",
"Pursuit Ship (19xx)(-)",
"Q-Bertus (19xx)(-)(de)",
"Quadrato (19xx)(-)(de)",
"Quadrato (19xx)(-)(de)[a]",
"Quake (1998)(CSSCGC)",
"R0bb0 (demo) (1997)(Zer0)",
"Ravine (19xx)(-)",
"Reaction Time (1996)(CSSCGC)",
"Really Smart Game (1999)(CSSCGC)",
"Recopilacion Vives (19xx)(-)(es)",
"Reversi (19xx)(-)",
"Reversi (19xx)(-)(de)",
"Reversi (19xx)(-)(sr)",
"Ring Master (19xx)(-)",
"Ring Master (19xx)(-)[a]",
"Rings of Saturn, The (19xx)(-)",
"Road Runner (1983)(Protek Computing)",
"Robotank (19xx)(-)",
"RoboXonix (1994)(Chemist Soft)[h Spectrum Warriors]",
"Rubics Wurfel (1982)(-)(de)[aka Acme Glass Cube]",
"S.O.S. (1984)(Visions Software Factory)",
"Sabo (19xx)(-)",
"Sacred Sword (1990)(Topo Soft)(es)[cr Kicia]",
"Saltamonte Saltarin (19xx)(-)(es)[16K]",
"Santa's Search (19xx)(-)",
"Scissors, Paper, Stone (1999)(CSSCGC)",
"Scuba Dive (1984)(-)[re-release]",
"Season Ticket (19xx)(-)",
"Senso (19xx)(-)(de)",
"Serpenti (1986)(-)",
"Sex Tetris 2 (19xx)(-)(ru)[h Seamans]",
"Shadow Service Monitor (1997)(-)[h Omega Guard]",
"Shashki (19xx)(X-Project Association)(ru)",
"Shoot That Tank (1996)(CSSCGC)",
"Sigfrido (1987)(New Frontier)(es)",
"Simon (19xx)(-)",
"Sink the Belgrano (1997)(CSSCGC)",
"Sir Lion (1987)(Firebird Software)",
"Skiing (1996)(CSSCGC)",
"Skinhead (1998)(CSSCGC)",
"Slalom (19xx)(-)",
"Slog, The (19xx)(-)[h Ascendancy]",
"Snakes and Adders (1997)(CSSCGC)",
"Sokoban v1.0 (1996)(CSSCGC)",
"Sorti (1984)(-)",
"Space Invaders 2 (19xx)(-)(de)[16K]",
"Space Observer (19xx)(-)",
"Speccy Simon (1996)(CSSCGC)",
"Speccy Simon (1996)(CSSCGC)[a]",
"SpecDaleks (1996)(CSSCGC)",
"Spectrum-Skat (1983)(-)(de)",
"Spellcaster (19xx)(-)",
"Spellcaster (19xx)(-)[a]",
"Spielautomaten (19xx)(-)(de)",
"Splash (19xx)(-)",
"Sprl Tower (19xx)(-)",
"Squad Quick Reaction (1994)(Chip - Rocky)(ru)[h Digital Reality][t]",
"Squamble (19xx)(-)",
"Squash (1997)(CSSCGC)",
"Stadt Alzan, Die (19xx)(-)(de)",
"Starcraft (demo) (2002)(-)",
"Stars 2 (1996)(CSSCGC)",
"Stars 3 (1996)(CSSCGC)",
"Stock Market (19xx)(-)",
"Stranded (19xx)(-)",
"Stuntman (1996)(CSSCGC)",
"Supalanda (19xx)(-)",
"Super Bomber (1997)(CSSCGC)",
"Super League (19xx)(-)",
"Super League - World Cup (19xx)(-)",
"Super Star Trek (19xx)(-)",
"Surround (1996)(CSSCGC)",
"T. Devil (19xx)(Theo Devil)(Part 1 of 2)[a][hack of Nosferatu the Vampyre]",
"T. Devil (19xx)(Theo Devil)(Part 1 of 2)[hack of Nosferatu the Vampyre]",
"T. Devil (19xx)(Theo Devil)(Part 2 of 2)[a][hack of Nosferatu the Vampyre]",
"T. Devil (19xx)(Theo Devil)(Part 2 of 2)[hack of Nosferatu the Vampyre]",
"Tank Assault (1989)(E&J Software)",
"Tarantulas (19xx)(-)(es)",
"Target (1997)(CSSCGC)",
"Teddy Bear (1987)(Traff's Software)",
"Tennis (1996)(CSSCGC)",
"Terrometer (1987)(Codemasters)",
"Test, The (19xx)(-)",
"Tetris - The Text Adventure (1996)(CSSCGC)",
"TEWShips (1996)(CSSCGC)",
"That Pythonesque Foot (1998)(CSSCGC)[128K]",
"Time Quest (1985)(Double Play Adventures)",
"Tinderbox (1985)(-)",
"Tinderbox (1985)(-)[a]",
"Top Secret (19xx)(-)",
"Top Secret (19xx)(-)[a]",
"Topo, El (1989)(-)(es)",
"Topo, El (1989)(-)(es)[a]",
"Torens van Hanoi (1984)(Book)(nl)",
"Tour of the Knight (1997)(CSSCGC)",
"Tourist Trap (19xx)(-)",
"Tourist Trap (19xx)(-)[a]",
"Trader (1990)(F. Shillito)",
"Trail Racer (1988)(-)",
"Trank (19xx)(-)",
"Trebuchet (1998)(CSSCGC)[128K]",
"Tren 8 (19xx)(-)(es)",
"Tron (19xx)(-)(de)",
"Tronn (19xx)(-)(de)",
"Tunnel Raider (19xx)(-)",
"Turbo Racers (1996)(CSSCGC)",
"Ufo (19xx)(MCT)(bs)",
"Universa (1991)(Tawkeht)(ru)[128K]",
"Universal (1991)(-)(ru)",
"Upir (19xx)(-)(cs)[128K]",
"UTE (1984)(-)",
"Valley Racer 3D (1996)(CSSCGC)",
"Vampiro (19xx)(-)",
"Verdugo (19xx)(-)(es)",
"Verdugo (19xx)(-)(es)[a]",
"Vier op een Rij (1983)(Book)(nl)[16K]",
"Vinny Puh (1996)(VB)(ru)[h Digital Reality]",
"Vinny Puh (1996)(VB)(ru)[h Seamans][t]",
"Vinny Puh (1996)(VB)(ru)[h Spectrum Warriors][t]",
"Vision (19xx)(-)",
"Vyesu (demo) (19xx)(-)(ru)",
"Wacky Zany Painter Guy (1996)(CSSCGC)",
"War-Lord (19xx)(-)[128K]",
"Washing Day (1996)(CSSCGC)",
"Wheelchair (1997)(CSSCGC)",
"Wimbledon '97 (1997)(CSSCGC)",
"Wizard, The (1984)(Aquarius)(de)",
"World Cup (1990)(D&H Games)",
"World War 2.5 - Hitler's Revenge (1998)(CSSCGC)",
"Worm, The (1997)(CSSCGC)",
"Wuestenkrieg (19xx)(-)(de)",
"Wurmi (19xx)(-)(de)[16K]",
"Yahtzee (19xx)(-)",
"ZxZvm - A Bear's Night Out - An Interactive Children's Story (1999)(David Dyte)",
"ZxZvm - A Change in the Weather - An Interactive Short Story (1996)(Andrew Plotkin)",
"ZxZvm - A Good Breakfast - An Interactive Feeding (1997)(Stuart Adair)",
"ZxZvm - A New Day (19xx)(Jonathan Fry)",
"ZxZvm - A Week in the Life - An Interactive Self (1998)(Neil James Brown)",
"ZxZvm - Abenteur - Das Interaktive Original (1998)(Toni Arnold)(de)[aka Adventure - The Interactive Original]",
"ZxZvm - Acid Whiplash (1998)(Rybread Celsius - Cody Sandifer)",
"ZxZvm - Acorn Court - An Interactive Text Adventure (1997)(Todd S. Murchison)",
"ZxZvm - Adventure - The Interactive Original (1994)(Graham Nelson)",
"ZxZvm - All Quiet on the Library Front - An Interactive Vignette (1995)(Michael S.Phillips)",
"ZxZvm - Anchorhead - An Interactive Tale of Lovecraftian Horror (1998)(Michael S. Gentry)",
"ZxZvm - Annoyed Undead - An Inventoryless Adventure (1999)(Roger Ostrander)",
"ZxZvm - Apartment 209 - An Interactive Pigsty (1997)(Ben Parrish)",
"ZxZvm - Aunt Nancy's House - An Interactive Simulation (1997)(Nate Schwartzman)",
"ZxZvm - Baer Geht aus Ein - Eine Interaktive Kindergeschichte (1998)(Gunther Schmidl)(de)[aka A Bear's Night Out]",
"ZxZvm - Balances - An Interactive Short Story (1996)(Graham Nelson)",
"ZxZvm - Ballyhoo (1986)(Infocom)",
"ZxZvm - Baltimore 24 - An Exercise in Interactive Fiction (1997)(Howard A. Sherman)",
"ZxZvm - Bedlam - An Interactive Preview (1997)(Michael Zey)",
"ZxZvm - Bloodline - An Interactive Coming-of-Age (1998)(Liza Daly)",
"ZxZvm - Blow Job Drifter - An Interactive You Know What (1998)(Big Al)",
"ZxZvm - Border Zone - A Game of Intrigue (1987)(Infocom)",
"ZxZvm - BSE - An Interactive Epidemic (1996)(Chris Smith)",
"ZxZvm - Busted! - Psychedelic Interactive Fiction (1994)(Jon Drukman)",
"ZxZvm - C.I.A. Adventure (1996)(Kevin Thomas)",
"ZxZvm - Candy - An Attempt at Reliving Childhood (1997)(Rybread Celsius)",
"ZxZvm - Cask - My First Stab at Interactive Fiction (1997)(Harry M. Hardjono)",
"ZxZvm - Cattus Atrox - An Interactive Fiction Story (1998)(David A. Cornelson)",
"ZxZvm - Chicken Under the Window - An Interactive Farce (1998)(Lucian Smith)",
"ZxZvm - Christminster - An Interactive Conspiracy (1995)(Gareth Rees)",
"ZxZvm - Coke is It! - An Interactive Commercial (1999)(Soda Pop Productions)",
"ZxZvm - Coming Home - A Simple Home Adventure (1997)(Andrew Katz)",
"ZxZvm - Competition 96 - An Interactive Guide (1997)(Lucian Smith)",
"ZxZvm - Congratulations! (1997)(Frederick J. Hirsch)",
"ZxZvm - Cutthroats (1984)(Infocom)",
"ZxZvm - Deadline - An Interlogic Mystery (1982)(Infocom)",
"ZxZvm - Deja Vu - An Interactive Demonstration (1993)(Graham Nelson)",
"ZxZvm - Delusions - An Interactive Self Discovery (1996)(Christopher E. Forman)",
"ZxZvm - Detective (1998)(Stuart Moore)",
"ZxZvm - Downtown Tokyo Present Day (1998)(Digby McWiggle)",
"ZxZvm - Enchanter - Interlogic Fantasy (1983)(Infocom)",
"ZxZvm - Encyclopedia Frobozzica (19xx)(Digby McWiggle)",
"ZxZvm - Enemies - An Interactive Psychothriller (1999)(Andy Phillips)",
"ZxZvm - Fear - An Interactive Nightmare (1996)(Chuan-Tze Teo)",
"ZxZvm - Fifteen (1998)(Ricardo Dague)",
"ZxZvm - Friday Afternoon or Escape from MicroSun (1997)(Mischa Schweitzer)",
"ZxZvm - Frozen - A Night at the Lab (1996)(Jeremy Farnham)",
"ZxZvm - Gumshoe - An Interactive Investigation (1996)(Mike Oliphant)",
"ZxZvm - Heist - The Crime of the Century (1997)(Andy Phillips)",
"ZxZvm - Hitchhiker's Guide to the Galaxy - A Science Fiction Story (1984)(Infocom)",
"ZxZvm - Hitchhiker's Guide to the Galaxy - Solid Gold Edition - A Science Fiction Story (1987)(Infocom)",
"ZxZvm - Hollywood Hijinx - A Zany Treasure Hunt (1986)(Infocom)",
"ZxZvm - Human Resources Stories - In Search of Employment (1998)(Harry M. Hardjono)",
"ZxZvm - I-0 - Jailbait on Interstate Zero v1.21 (1997)(Adam Cadre)",
"ZxZvm - In the End (1996)(Joe Mason)",
"ZxZvm - In the SpotLight - An Unexpected Intelligence Test (1998)(John Byrd)",
"ZxZvm - Infidel (1983)(Infocom)",
"ZxZvm - Infocom Sampler 1 (1984)(Infocom)",
"ZxZvm - Infocom Sampler 1 - Newer (1987)(Infocom)",
"ZxZvm - Infocom Sampler 2 (1987)(Infocom)",
"ZxZvm - Informatory - A Not Very Interactive Pastiche with Tutorial Pretensions (1998)(William J. Shlaer)",
"ZxZvm - Inhumane - An Infralogic Massacre (19xx)(Andrew Plotkin)",
"ZxZvm - Intruder - Interactive Fiction - A Burglary (1999)(Volker Lanz)",
"ZxZvm - It's a Dog's Life - An Interactive Heeling (1999)(Mr. Wigglebutt)",
"ZxZvm - Jigsaw - An Interactive History (1995)(Graham Nelson)",
"ZxZvm - Journey to Alpha Centauri in Real Time - An Interactive Waste of Time (1998)(Julian Fleetwood)",
"ZxZvm - Kook U - An Interactive Kook Adventure (1997)(SBFAQ)",
"ZxZvm - Lack of Vision - An Eye Opening Demo (1998)(Rybread Celsius)",
"ZxZvm - Leather Godesses of Phobos - A Racy Space-Age Spoof (1986)(Infocom)",
"ZxZvm - Limp - An Interactive Thingy (1998)(Rybread Celsius)",
"ZxZvm - Lists and Lists - An Interactive Tutorial (1996)(Andrew Plotkin)",
"ZxZvm - Little Blue Men - An Interactive Object Lesson (1998)(Michael S. Gentry)",
"ZxZvm - Looking for Godot - An Interactive Looking-Around-for-a-Lost-English-Book (1996)(Patrick Shaughnessy)",
"ZxZvm - Mercy - A Short Story (1998)(Christopher Klimas)",
"ZxZvm - Moonmist - A Mystery Story (1986)(Infocom)",
"ZxZvm - Mother Loose - An Interactive Nursery Rhyme (1998)(Irene Callaci)",
"ZxZvm - Muse - An Autumn Romance (1998)(Christopher Huang)",
"ZxZvm - Night at the Computer Center - An Interactive Nocturnal Chase (1996)(Bonni Mierzejewska)",
"ZxZvm - Nine Points - A Demonstration of an Interactive Fiction (1996)(Robert Janelle - Brad O'Donnell)",
"ZxZvm - Odieu's Quest for the Magic Flingshot (1994)(Teo Kwang Liak)(beta)",
"ZxZvm - Of Forms Unknown - An Interactive Excursion (1996)(Chris Markwyn)",
"ZxZvm - Paper Chase - An Interactive Education (1995)(Chris Skapura)",
"ZxZvm - Pentari - An Interactive Prequel to The Mission (1998)(Howard Sherman)",
"ZxZvm - Phlegm - An Interactive Interactive (1997)(Jason Dyer)",
"ZxZvm - Photopia (19xx)(Adam Cadre)",
"ZxZvm - Phred Phontious and the Quest for Pizza - An Interactive Errand (1997)(Michael Zey)",
"ZxZvm - Pick Up the Phone Booth and Die - A NyQuil Nightmare (1996)(R. Noyes)",
"ZxZvm - Pick Up the Phone Booth and Die 2 - An Interactive Demo (1996)(R. Noyes)",
"ZxZvm - Piece of Mind - An Interactive Short Story (1995)(Giles Boutel)",
"ZxZvm - Pintown (19xx)(Stefan Blixt)",
"ZxZvm - Planetfall - Interlogic Science Fiction (1983)(Infocom)",
"ZxZvm - Plundered Hearts (1987)(Infocom)",
"ZxZvm - Quest for the Magic Healing Plant (1996)(Adam G. Crutchlow)",
"ZxZvm - Ralph - An Interactive Sniffing (1998)(Miron Schmidt)",
"ZxZvm - Research Dig (1998)(Chris Armitage)",
"ZxZvm - Return to Karn (1996)(Patrick Wigfull)",
"ZxZvm - Reverberations - A Hectic Voltairian Adventure (1996)(Russell Glasser)",
"ZxZvm - Rippled Flesh - An Interactive Goosing (1996)(Rybread Celsius)",
"ZxZvm - Ritual of Purification - An Interactive Cleansing (1998)(Sable)",
"ZxZvm - Seastalker - A Junior Adventure (1984)(Infocom)",
"ZxZvm - Sherlock - The Riddle of the Crown Jewels (1987)(Infocom)",
"ZxZvm - Silence of the Lambs - An Interactive Horror (1997)(Gunther Schmidl)",
"ZxZvm - Sins Against Mimesis - An Interactive Theosophy (1997)(Adam Thornton)",
"ZxZvm - Slacker X - A Scatological Breakthrough in Adventure Gaming (1997)(Satin Shiva Productions)",
"ZxZvm - So Far - An Interactive Catharsis (1996)(Andrew Plotkin)",
"ZxZvm - SoftPorn Adventure - An Interactive Classic (1997)(Chuck Benton)",
"ZxZvm - Sorcerer - Interlogic Fantasy (19xx)(Infocom)",
"ZxZvm - Space Station - A Science Fiction Story (1999)(David Ledgard)",
"ZxZvm - Space Under the Window (1997)(Andrew Plotkin)",
"ZxZvm - Spellbreaker - An Interactive Fantasy (1985)(Infocom)",
"ZxZvm - SpiritWrak - An Interactive Fantasy Adventure (1996)(Daniel S. Yu)",
"ZxZvm - Starcross - Interlogic Science Fiction (1982)(Infocom)",
"ZxZvm - Stargazer - Prologue - An Adventure in Outfitting (1996)(Jonathan Fry)",
"ZxZvm - Stationfall - A Science Fiction Story (1987)(Infocom)",
"ZxZvm - Suspect - An Interactive Mystery (1984)(Infocom)",
"ZxZvm - Suspended - Interlogic Science Fiction (1983)(Infocom)",
"ZxZvm - Symetry - A Matter of Self Trust (1997)(Rybread Celsius)",
"ZxZvm - Tangle - Spider and Web - Interactive Fiction (1998)(Andrew Plotkin)",
"ZxZvm - The City v2 - An Interactive Short Experience (19xx)(Sam Barlow)",
"ZxZvm - The Edifice - An Interactive Allegory (1997)(Lucian Smith)",
"ZxZvm - The Family Legacy - An Interactive Ghost Story v1.1 (1997)(Marnie Parker)",
"ZxZvm - The Ice Princess - An Interactive Fairy-Tale (1996)(Ruediger Hanke)",
"ZxZvm - The Lost Spellmaker - An Interactive Mission (1998)(Neil James Brown)",
"ZxZvm - The Lurking Horror - An Interactive Horror (1987)(Infocom)",
"ZxZvm - The Magic Toyshop - A Fun Game for all the Family (1995)(Gareth Rees)",
"ZxZvm - The Meteor, the Stone and a Long Glass of Sherbet (1996)(Graham Nelson)",
"ZxZvm - The Mind Electric - An Interactive Vision (1995)(Jason Dyer)",
"ZxZvm - The Night of the Vampire Bunnies (1997)(Jason Dyer)",
"ZxZvm - The Six-Foot-Tall Man-Eating Chicken (1999)(Ryan N. Freebern)",
"ZxZvm - The Town Dragon - Interactive Fiction (1997)(David A. Cornelson)",
"ZxZvm - The Underoos That Ate New York! - An Interactive Quickie (1994)(Gerry Kevin Wilson)",
"ZxZvm - The Wedding - An Interactive Family Headache (1997)(Neil James Brown)",
"ZxZvm - Time Killer 1 - Claustrophobia (1995)(Sam Hulick)",
"ZxZvm - Total Padding Mania - An Interactive Punishment Jag (19xx)(Aloysius Beltway)",
"ZxZvm - Trapped in a One-Room Dilly (1998)(Laura A. Knauth)",
"ZxZvm - Tryst of Fate - An Interactive Horse Opera (1997)(Gregory M. Zagurski)",
"ZxZvm - Tube Trouble - A Mini Adventure (1995)(Richard Tucker)",
"ZxZvm - Vindaloo - An Interactive Recipe (1996)(Adam G. Crutchlow)",
"ZxZvm - Wearing the Claw (1997)(Paul O'Brian)",
"ZxZvm - Welcome to Hell (1998)(Kevin Norton - Brandon Myers)",
"ZxZvm - Where Evil Dwells (1998)(Paul Johnson - Steve Owens)",
"ZxZvm - Windhall Chronicles Volume One - The Path to Fortune (1996)(Jeff Cassidy - Christopher E. Forman)",
"ZxZvm - Wishbringer - Interactive Fantasy for Beginners (1985)(Infocom)",
"ZxZvm - Witness - An Interlogic Mystery (1983)(Infocom)",
"ZxZvm - Zork - A Troll's Eye View - An Interactive Tedium (1998)(Dylan O'Donnell)",
"ZxZvm - Zork - The Undiscovered Underground (1997)(Activision)",
"ZxZvm - Zork I - The Great Underground Empire (1984)(Infocom)",
"ZxZvm - Zork I - The Great Underground Empire (1984)(Infocom)",
"ZxZvm - Zork I - The Great Underground Empire - Solid Gold Edition (1987)(Infocom)",
"ZxZvm - Zork II - The Wizard of Frobozz (1984)(Infocom)",
"ZxZvm - Zork III - The Dungeon Master (1984)(Infocom)",
"ZxZvm - Zuni Doll - An Interactive Horror Story (1997)(Jesse Burneko)",
"ZZZ-UNK-Ace Code (19xx)(-)",
"ZZZ-UNK-Allo Call (19xx)(-)",
"ZZZ-UNK-BATTLE (19xx)(-)",
"ZZZ-UNK-dr_plzak (19xx)(-)",
"ZZZ-UNK-Fytale (danish)",
"ZZZ-UNK-sexsyp (19xx)(-)(de)",
"ZZZ-UNK-underwurlde (Ultimate Play The Game)(s1)",
"ZZZ-UNK-unk (-)[b]",
"ZZZ-UNK-val (19xx)(-)",
"ZZZ-UNK-worldral (1988)",
"ZZZ-UNK-Yoursinc (19xx)(-)",

];

module.exports = {
missing: missing
}
